// <auto-generated />
using System;
using CleanArchitecture.Template.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Template.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240817195631_WeatherForecastInitialMigration")]
    partial class WeatherForecastInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.Template.Domain.Entities.WeatherForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5229527d-cea0-43a2-b14f-3e714bb6e0fb"),
                            Summary = "Cool"
                        },
                        new
                        {
                            Id = new Guid("e709a49a-2ca8-418f-bad4-3aa58f0041e1"),
                            Summary = "Chilly"
                        },
                        new
                        {
                            Id = new Guid("c46f97e2-8b6c-4c67-97d5-b9224c374cee"),
                            Summary = "Mild"
                        },
                        new
                        {
                            Id = new Guid("9aec4c12-0917-43e7-ac68-30b76b473b54"),
                            Summary = "Scorching"
                        },
                        new
                        {
                            Id = new Guid("0851bbdc-cf71-4009-9ba2-d4b1020e4aa8"),
                            Summary = "Scorching"
                        },
                        new
                        {
                            Id = new Guid("30eeeaee-12b4-4176-88a5-0045e32bcb6b"),
                            Summary = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("cd25b402-d580-46e4-b3fa-f0ccd4d0c34c"),
                            Summary = "Balmy"
                        },
                        new
                        {
                            Id = new Guid("4583e970-640c-409b-85eb-8bd5fb84ae4d"),
                            Summary = "Freezing"
                        },
                        new
                        {
                            Id = new Guid("00a63995-a7e4-42b2-8408-a31f5fc8abbf"),
                            Summary = "Freezing"
                        },
                        new
                        {
                            Id = new Guid("28259e9d-fa7d-4915-baa7-85cba9ca31d2"),
                            Summary = "Scorching"
                        },
                        new
                        {
                            Id = new Guid("4c1ba407-415e-4894-a489-d1f9541ea658"),
                            Summary = "Hot"
                        },
                        new
                        {
                            Id = new Guid("b7ee5b3a-e2ef-4aa5-9fe1-e9bac4f46ab2"),
                            Summary = "Chilly"
                        },
                        new
                        {
                            Id = new Guid("bdea3223-7e74-42dc-9daa-90602e60e403"),
                            Summary = "Warm"
                        },
                        new
                        {
                            Id = new Guid("c7d15f40-1ac1-4b53-a0e5-7401aa095687"),
                            Summary = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("9c7212f2-28b4-4ef2-bb15-16d60b9863eb"),
                            Summary = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("b4315a8a-af9f-4966-ab77-c6bce7dbfc27"),
                            Summary = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("19775645-82a7-4f10-917d-5a1e82c403f2"),
                            Summary = "Hot"
                        },
                        new
                        {
                            Id = new Guid("831d8fda-64ce-414b-8ecc-1a90dc9f51ad"),
                            Summary = "Warm"
                        },
                        new
                        {
                            Id = new Guid("4e844bd9-f72d-41ea-9939-713fe9198b20"),
                            Summary = "Warm"
                        },
                        new
                        {
                            Id = new Guid("834debb2-fd24-4b4f-8c5a-11f0a9926976"),
                            Summary = "Unknown"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Template.Domain.Entities.WeatherForecast", b =>
                {
                    b.OwnsOne("CleanArchitecture.Template.SharedKernel.CommonTypes.ValueObjects.Temperature", "Temperature", b1 =>
                        {
                            b1.Property<Guid>("WeatherForecastId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TemperatureType");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("TemperatureValue");

                            b1.HasKey("WeatherForecastId");

                            b1.ToTable("WeatherForecasts");

                            b1.WithOwner()
                                .HasForeignKey("WeatherForecastId");

                            b1.HasData(
                                new
                                {
                                    WeatherForecastId = new Guid("5229527d-cea0-43a2-b14f-3e714bb6e0fb"),
                                    Type = "Fahrenheit",
                                    Value = 22.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("e709a49a-2ca8-418f-bad4-3aa58f0041e1"),
                                    Type = "Fahrenheit",
                                    Value = 21.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("c46f97e2-8b6c-4c67-97d5-b9224c374cee"),
                                    Type = "Fahrenheit",
                                    Value = 1.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("9aec4c12-0917-43e7-ac68-30b76b473b54"),
                                    Type = "Celsius",
                                    Value = 15.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("0851bbdc-cf71-4009-9ba2-d4b1020e4aa8"),
                                    Type = "Celsius",
                                    Value = 22.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("30eeeaee-12b4-4176-88a5-0045e32bcb6b"),
                                    Type = "Fahrenheit",
                                    Value = -1.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("cd25b402-d580-46e4-b3fa-f0ccd4d0c34c"),
                                    Type = "Celsius",
                                    Value = 2.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("4583e970-640c-409b-85eb-8bd5fb84ae4d"),
                                    Type = "Celsius",
                                    Value = -3.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("00a63995-a7e4-42b2-8408-a31f5fc8abbf"),
                                    Type = "Fahrenheit",
                                    Value = 13.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("28259e9d-fa7d-4915-baa7-85cba9ca31d2"),
                                    Type = "Fahrenheit",
                                    Value = 22.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("4c1ba407-415e-4894-a489-d1f9541ea658"),
                                    Type = "Fahrenheit",
                                    Value = 22.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("b7ee5b3a-e2ef-4aa5-9fe1-e9bac4f46ab2"),
                                    Type = "Fahrenheit",
                                    Value = 29.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("bdea3223-7e74-42dc-9daa-90602e60e403"),
                                    Type = "Fahrenheit",
                                    Value = 12.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("c7d15f40-1ac1-4b53-a0e5-7401aa095687"),
                                    Type = "Fahrenheit",
                                    Value = 25.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("9c7212f2-28b4-4ef2-bb15-16d60b9863eb"),
                                    Type = "Fahrenheit",
                                    Value = -1.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("b4315a8a-af9f-4966-ab77-c6bce7dbfc27"),
                                    Type = "Fahrenheit",
                                    Value = 9.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("19775645-82a7-4f10-917d-5a1e82c403f2"),
                                    Type = "Celsius",
                                    Value = 1.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("831d8fda-64ce-414b-8ecc-1a90dc9f51ad"),
                                    Type = "Fahrenheit",
                                    Value = 10.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("4e844bd9-f72d-41ea-9939-713fe9198b20"),
                                    Type = "Fahrenheit",
                                    Value = 32.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("834debb2-fd24-4b4f-8c5a-11f0a9926976"),
                                    Type = "Celsius",
                                    Value = 9.0
                                });
                        });

                    b.OwnsOne("CleanArchitecture.Template.SharedKernel.CommonTypes.ValueObjects.WeatherDate", "Date", b1 =>
                        {
                            b1.Property<Guid>("WeatherForecastId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("Date");

                            b1.HasKey("WeatherForecastId");

                            b1.ToTable("WeatherForecasts");

                            b1.WithOwner()
                                .HasForeignKey("WeatherForecastId");

                            b1.HasData(
                                new
                                {
                                    WeatherForecastId = new Guid("5229527d-cea0-43a2-b14f-3e714bb6e0fb"),
                                    Value = new DateOnly(2022, 7, 12)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("e709a49a-2ca8-418f-bad4-3aa58f0041e1"),
                                    Value = new DateOnly(2025, 11, 25)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("c46f97e2-8b6c-4c67-97d5-b9224c374cee"),
                                    Value = new DateOnly(2026, 2, 23)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("9aec4c12-0917-43e7-ac68-30b76b473b54"),
                                    Value = new DateOnly(2025, 4, 28)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("0851bbdc-cf71-4009-9ba2-d4b1020e4aa8"),
                                    Value = new DateOnly(2026, 7, 12)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("30eeeaee-12b4-4176-88a5-0045e32bcb6b"),
                                    Value = new DateOnly(2022, 12, 24)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("cd25b402-d580-46e4-b3fa-f0ccd4d0c34c"),
                                    Value = new DateOnly(2026, 4, 4)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("4583e970-640c-409b-85eb-8bd5fb84ae4d"),
                                    Value = new DateOnly(2023, 12, 27)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("00a63995-a7e4-42b2-8408-a31f5fc8abbf"),
                                    Value = new DateOnly(2026, 6, 20)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("28259e9d-fa7d-4915-baa7-85cba9ca31d2"),
                                    Value = new DateOnly(2024, 7, 5)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("4c1ba407-415e-4894-a489-d1f9541ea658"),
                                    Value = new DateOnly(2022, 3, 7)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("b7ee5b3a-e2ef-4aa5-9fe1-e9bac4f46ab2"),
                                    Value = new DateOnly(2025, 11, 27)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("bdea3223-7e74-42dc-9daa-90602e60e403"),
                                    Value = new DateOnly(2022, 3, 25)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("c7d15f40-1ac1-4b53-a0e5-7401aa095687"),
                                    Value = new DateOnly(2023, 2, 17)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("9c7212f2-28b4-4ef2-bb15-16d60b9863eb"),
                                    Value = new DateOnly(2027, 2, 7)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("b4315a8a-af9f-4966-ab77-c6bce7dbfc27"),
                                    Value = new DateOnly(2027, 1, 26)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("19775645-82a7-4f10-917d-5a1e82c403f2"),
                                    Value = new DateOnly(2022, 1, 1)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("831d8fda-64ce-414b-8ecc-1a90dc9f51ad"),
                                    Value = new DateOnly(2023, 4, 30)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("4e844bd9-f72d-41ea-9939-713fe9198b20"),
                                    Value = new DateOnly(2023, 1, 9)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("834debb2-fd24-4b4f-8c5a-11f0a9926976"),
                                    Value = new DateOnly(2025, 7, 19)
                                });
                        });

                    b.Navigation("Date")
                        .IsRequired();

                    b.Navigation("Temperature")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
