// <auto-generated />
using System;
using CleanArchitecture.Template.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Template.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240805000600_SeedDefaultDataWeatherForecast")]
    partial class SeedDefaultDataWeatherForecast
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.Template.Domain.Entities.WeatherForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fc746ef-fe20-477f-bc2c-cba82b790f4f"),
                            Summary = "Freezing"
                        },
                        new
                        {
                            Id = new Guid("e4001aa6-3358-46b6-84a5-2e423ce90b94"),
                            Summary = "Bracing"
                        },
                        new
                        {
                            Id = new Guid("8fa85d80-c8bd-493b-a170-011d0cc1398e"),
                            Summary = "Warm"
                        },
                        new
                        {
                            Id = new Guid("d75ce0bf-657e-4baf-aa21-0bb1b73cd5f8"),
                            Summary = "Warm"
                        },
                        new
                        {
                            Id = new Guid("5cc7ff59-f867-457e-b2db-958e89626327"),
                            Summary = "Sweltering"
                        },
                        new
                        {
                            Id = new Guid("8c2f0c14-0518-4772-8ffa-f15478fc9216"),
                            Summary = "Balmy"
                        },
                        new
                        {
                            Id = new Guid("00668c3b-da72-4897-b2b7-088fc07745bd"),
                            Summary = "Bracing"
                        },
                        new
                        {
                            Id = new Guid("da5e3eb1-5b2f-46dc-8a0c-d1d0156f541b"),
                            Summary = "Scorching"
                        },
                        new
                        {
                            Id = new Guid("b415650c-320e-46e8-97dd-cbb9e891815f"),
                            Summary = "Freezing"
                        },
                        new
                        {
                            Id = new Guid("346c709a-bcc1-4fd5-bb21-af107be7ae08"),
                            Summary = "Balmy"
                        },
                        new
                        {
                            Id = new Guid("81e65eef-eae4-449d-bdea-6d4493b3c773"),
                            Summary = "Bracing"
                        },
                        new
                        {
                            Id = new Guid("db492ae0-b851-42d6-8f59-ce69ca810538"),
                            Summary = "Balmy"
                        },
                        new
                        {
                            Id = new Guid("468d7d47-dd40-45e1-b3bf-59dfea65793b"),
                            Summary = "Cool"
                        },
                        new
                        {
                            Id = new Guid("d86b61a8-1c3a-474b-9af9-83052cc48f98"),
                            Summary = "Mild"
                        },
                        new
                        {
                            Id = new Guid("609ab2ee-c99f-4970-9085-bb9d106e6793"),
                            Summary = "Balmy"
                        },
                        new
                        {
                            Id = new Guid("7e944825-5b9e-498d-8156-6bdc0b48c429"),
                            Summary = "Sweltering"
                        },
                        new
                        {
                            Id = new Guid("39aebc8f-28c7-46e7-9407-725d9a517521"),
                            Summary = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("e9fbb1f4-4465-41ea-9816-0e2ced492072"),
                            Summary = "Chilly"
                        },
                        new
                        {
                            Id = new Guid("0dae66ae-2301-46c0-9a73-acc00cccc502"),
                            Summary = "Cool"
                        },
                        new
                        {
                            Id = new Guid("14b4bf5e-9c5c-44ee-a149-5ad5adcc0c26"),
                            Summary = "Cool"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Template.Domain.Entities.WeatherForecast", b =>
                {
                    b.OwnsOne("CleanArchitecture.Template.Domain.ValueObjects.Temperature", "Temperature", b1 =>
                        {
                            b1.Property<Guid>("WeatherForecastId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("TemperatureType");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("TemperatureValue");

                            b1.HasKey("WeatherForecastId");

                            b1.ToTable("WeatherForecasts");

                            b1.WithOwner()
                                .HasForeignKey("WeatherForecastId");

                            b1.HasData(
                                new
                                {
                                    WeatherForecastId = new Guid("0fc746ef-fe20-477f-bc2c-cba82b790f4f"),
                                    Type = 0,
                                    Value = 12.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("e4001aa6-3358-46b6-84a5-2e423ce90b94"),
                                    Type = 0,
                                    Value = -3.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("8fa85d80-c8bd-493b-a170-011d0cc1398e"),
                                    Type = 0,
                                    Value = 6.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("d75ce0bf-657e-4baf-aa21-0bb1b73cd5f8"),
                                    Type = 0,
                                    Value = 29.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("5cc7ff59-f867-457e-b2db-958e89626327"),
                                    Type = 0,
                                    Value = 34.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("8c2f0c14-0518-4772-8ffa-f15478fc9216"),
                                    Type = 0,
                                    Value = 22.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("00668c3b-da72-4897-b2b7-088fc07745bd"),
                                    Type = 0,
                                    Value = 21.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("da5e3eb1-5b2f-46dc-8a0c-d1d0156f541b"),
                                    Type = 0,
                                    Value = 7.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("b415650c-320e-46e8-97dd-cbb9e891815f"),
                                    Type = 0,
                                    Value = 17.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("346c709a-bcc1-4fd5-bb21-af107be7ae08"),
                                    Type = 0,
                                    Value = -5.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("81e65eef-eae4-449d-bdea-6d4493b3c773"),
                                    Type = 0,
                                    Value = 9.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("db492ae0-b851-42d6-8f59-ce69ca810538"),
                                    Type = 0,
                                    Value = 24.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("468d7d47-dd40-45e1-b3bf-59dfea65793b"),
                                    Type = 0,
                                    Value = 11.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("d86b61a8-1c3a-474b-9af9-83052cc48f98"),
                                    Type = 0,
                                    Value = 5.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("609ab2ee-c99f-4970-9085-bb9d106e6793"),
                                    Type = 0,
                                    Value = -3.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("7e944825-5b9e-498d-8156-6bdc0b48c429"),
                                    Type = 0,
                                    Value = 27.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("39aebc8f-28c7-46e7-9407-725d9a517521"),
                                    Type = 0,
                                    Value = 9.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("e9fbb1f4-4465-41ea-9816-0e2ced492072"),
                                    Type = 0,
                                    Value = 12.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("0dae66ae-2301-46c0-9a73-acc00cccc502"),
                                    Type = 0,
                                    Value = -4.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("14b4bf5e-9c5c-44ee-a149-5ad5adcc0c26"),
                                    Type = 0,
                                    Value = 26.0
                                });
                        });

                    b.OwnsOne("CleanArchitecture.Template.Domain.ValueObjects.WeatherDate", "Date", b1 =>
                        {
                            b1.Property<Guid>("WeatherForecastId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("Date");

                            b1.HasKey("WeatherForecastId");

                            b1.ToTable("WeatherForecasts");

                            b1.WithOwner()
                                .HasForeignKey("WeatherForecastId");

                            b1.HasData(
                                new
                                {
                                    WeatherForecastId = new Guid("0fc746ef-fe20-477f-bc2c-cba82b790f4f"),
                                    Value = new DateOnly(2024, 9, 23)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("e4001aa6-3358-46b6-84a5-2e423ce90b94"),
                                    Value = new DateOnly(2026, 9, 23)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("8fa85d80-c8bd-493b-a170-011d0cc1398e"),
                                    Value = new DateOnly(2026, 2, 10)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("d75ce0bf-657e-4baf-aa21-0bb1b73cd5f8"),
                                    Value = new DateOnly(2025, 10, 3)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("5cc7ff59-f867-457e-b2db-958e89626327"),
                                    Value = new DateOnly(2025, 10, 15)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("8c2f0c14-0518-4772-8ffa-f15478fc9216"),
                                    Value = new DateOnly(2026, 8, 8)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("00668c3b-da72-4897-b2b7-088fc07745bd"),
                                    Value = new DateOnly(2024, 1, 26)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("da5e3eb1-5b2f-46dc-8a0c-d1d0156f541b"),
                                    Value = new DateOnly(2023, 4, 22)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("b415650c-320e-46e8-97dd-cbb9e891815f"),
                                    Value = new DateOnly(2023, 7, 16)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("346c709a-bcc1-4fd5-bb21-af107be7ae08"),
                                    Value = new DateOnly(2023, 5, 17)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("81e65eef-eae4-449d-bdea-6d4493b3c773"),
                                    Value = new DateOnly(2023, 1, 7)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("db492ae0-b851-42d6-8f59-ce69ca810538"),
                                    Value = new DateOnly(2026, 1, 21)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("468d7d47-dd40-45e1-b3bf-59dfea65793b"),
                                    Value = new DateOnly(2022, 7, 16)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("d86b61a8-1c3a-474b-9af9-83052cc48f98"),
                                    Value = new DateOnly(2024, 10, 16)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("609ab2ee-c99f-4970-9085-bb9d106e6793"),
                                    Value = new DateOnly(2024, 7, 6)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("7e944825-5b9e-498d-8156-6bdc0b48c429"),
                                    Value = new DateOnly(2024, 12, 15)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("39aebc8f-28c7-46e7-9407-725d9a517521"),
                                    Value = new DateOnly(2024, 4, 8)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("e9fbb1f4-4465-41ea-9816-0e2ced492072"),
                                    Value = new DateOnly(2025, 3, 9)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("0dae66ae-2301-46c0-9a73-acc00cccc502"),
                                    Value = new DateOnly(2023, 3, 14)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("14b4bf5e-9c5c-44ee-a149-5ad5adcc0c26"),
                                    Value = new DateOnly(2026, 12, 15)
                                });
                        });

                    b.Navigation("Date")
                        .IsRequired();

                    b.Navigation("Temperature")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
