// <auto-generated />
using System;
using CleanArchitecture.Template.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Template.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240805153837_TemperatureTypeAsStringWeatherForecast")]
    partial class TemperatureTypeAsStringWeatherForecast
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.Template.Domain.Entities.WeatherForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5cc7ead-9261-4fa8-ada7-578e2ef80d8b"),
                            Summary = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("4fabdac5-48c5-4d42-9fba-ed17a5013e7d"),
                            Summary = "Chilly"
                        },
                        new
                        {
                            Id = new Guid("5f930764-66fd-413f-85e3-c013373e044f"),
                            Summary = "Sweltering"
                        },
                        new
                        {
                            Id = new Guid("0a2cd0d5-1224-45fd-9a41-814b95b0df26"),
                            Summary = "Sweltering"
                        },
                        new
                        {
                            Id = new Guid("615ec5de-7490-43f9-9de6-a33d095c62a5"),
                            Summary = "Balmy"
                        },
                        new
                        {
                            Id = new Guid("82c1c5b0-a65c-406a-bc79-8e8d8de58ef8"),
                            Summary = "Mild"
                        },
                        new
                        {
                            Id = new Guid("5f36a8ad-97e6-424d-ad93-a8019daf2d6a"),
                            Summary = "Sweltering"
                        },
                        new
                        {
                            Id = new Guid("b818ae64-8e64-437a-870b-62b8542b4b23"),
                            Summary = "Balmy"
                        },
                        new
                        {
                            Id = new Guid("39e6221d-fee0-42a2-bb94-1c9cc24843e8"),
                            Summary = "Bracing"
                        },
                        new
                        {
                            Id = new Guid("96d54ef4-fc11-43f1-b0b0-06a0e0378bfc"),
                            Summary = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("4686ebb6-3345-40b5-8ace-e1ad26fef857"),
                            Summary = "Cool"
                        },
                        new
                        {
                            Id = new Guid("c6597222-1302-4d8d-ab27-08f24a0cfbef"),
                            Summary = "Hot"
                        },
                        new
                        {
                            Id = new Guid("4ac266fc-117d-4dbe-b3d2-7f002f76e4f9"),
                            Summary = "Scorching"
                        },
                        new
                        {
                            Id = new Guid("251ab013-66b1-4ca8-9192-d50d7c971400"),
                            Summary = "Cool"
                        },
                        new
                        {
                            Id = new Guid("deecc17a-f088-4003-89e6-81c0c9b38d00"),
                            Summary = "Chilly"
                        },
                        new
                        {
                            Id = new Guid("46ce2aaa-f175-4268-a4cb-b66e4e581dd9"),
                            Summary = "Freezing"
                        },
                        new
                        {
                            Id = new Guid("b6a75246-6c38-409a-a630-0e157644b737"),
                            Summary = "Freezing"
                        },
                        new
                        {
                            Id = new Guid("3e5dca62-8777-4645-8f9f-2b0268c40a0f"),
                            Summary = "Sweltering"
                        },
                        new
                        {
                            Id = new Guid("fb2a5e54-d46b-4fd6-811f-c9e1e96d0325"),
                            Summary = "Cool"
                        },
                        new
                        {
                            Id = new Guid("7ee8f27c-e0b3-43a1-94c6-48d08c8ec2fd"),
                            Summary = "Unknown"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Template.Domain.Entities.WeatherForecast", b =>
                {
                    b.OwnsOne("CleanArchitecture.Template.SharedKernel.CommonTypes.ValueObjects.Temperature", "Temperature", b1 =>
                        {
                            b1.Property<Guid>("WeatherForecastId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("TemperatureValue");

                            b1.HasKey("WeatherForecastId");

                            b1.ToTable("WeatherForecasts");

                            b1.WithOwner()
                                .HasForeignKey("WeatherForecastId");

                            b1.HasData(
                                new
                                {
                                    WeatherForecastId = new Guid("a5cc7ead-9261-4fa8-ada7-578e2ef80d8b"),
                                    Type = "Celsius",
                                    Value = 25.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("4fabdac5-48c5-4d42-9fba-ed17a5013e7d"),
                                    Type = "Celsius",
                                    Value = 14.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("5f930764-66fd-413f-85e3-c013373e044f"),
                                    Type = "Celsius",
                                    Value = 16.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("0a2cd0d5-1224-45fd-9a41-814b95b0df26"),
                                    Type = "Celsius",
                                    Value = 11.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("615ec5de-7490-43f9-9de6-a33d095c62a5"),
                                    Type = "Celsius",
                                    Value = 15.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("82c1c5b0-a65c-406a-bc79-8e8d8de58ef8"),
                                    Type = "Celsius",
                                    Value = 6.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("5f36a8ad-97e6-424d-ad93-a8019daf2d6a"),
                                    Type = "Celsius",
                                    Value = 5.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("b818ae64-8e64-437a-870b-62b8542b4b23"),
                                    Type = "Celsius",
                                    Value = -1.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("39e6221d-fee0-42a2-bb94-1c9cc24843e8"),
                                    Type = "Celsius",
                                    Value = 21.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("96d54ef4-fc11-43f1-b0b0-06a0e0378bfc"),
                                    Type = "Celsius",
                                    Value = 1.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("4686ebb6-3345-40b5-8ace-e1ad26fef857"),
                                    Type = "Celsius",
                                    Value = 5.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("c6597222-1302-4d8d-ab27-08f24a0cfbef"),
                                    Type = "Celsius",
                                    Value = 5.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("4ac266fc-117d-4dbe-b3d2-7f002f76e4f9"),
                                    Type = "Celsius",
                                    Value = 34.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("251ab013-66b1-4ca8-9192-d50d7c971400"),
                                    Type = "Celsius",
                                    Value = 8.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("deecc17a-f088-4003-89e6-81c0c9b38d00"),
                                    Type = "Celsius",
                                    Value = 5.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("46ce2aaa-f175-4268-a4cb-b66e4e581dd9"),
                                    Type = "Celsius",
                                    Value = 25.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("b6a75246-6c38-409a-a630-0e157644b737"),
                                    Type = "Celsius",
                                    Value = 17.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("3e5dca62-8777-4645-8f9f-2b0268c40a0f"),
                                    Type = "Celsius",
                                    Value = 10.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("fb2a5e54-d46b-4fd6-811f-c9e1e96d0325"),
                                    Type = "Celsius",
                                    Value = 29.0
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("7ee8f27c-e0b3-43a1-94c6-48d08c8ec2fd"),
                                    Type = "Celsius",
                                    Value = 15.0
                                });
                        });

                    b.OwnsOne("CleanArchitecture.Template.SharedKernel.CommonTypes.ValueObjects.WeatherDate", "Date", b1 =>
                        {
                            b1.Property<Guid>("WeatherForecastId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("Date");

                            b1.HasKey("WeatherForecastId");

                            b1.ToTable("WeatherForecasts");

                            b1.WithOwner()
                                .HasForeignKey("WeatherForecastId");

                            b1.HasData(
                                new
                                {
                                    WeatherForecastId = new Guid("a5cc7ead-9261-4fa8-ada7-578e2ef80d8b"),
                                    Value = new DateOnly(2026, 2, 24)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("4fabdac5-48c5-4d42-9fba-ed17a5013e7d"),
                                    Value = new DateOnly(2024, 4, 12)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("5f930764-66fd-413f-85e3-c013373e044f"),
                                    Value = new DateOnly(2025, 12, 15)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("0a2cd0d5-1224-45fd-9a41-814b95b0df26"),
                                    Value = new DateOnly(2027, 2, 28)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("615ec5de-7490-43f9-9de6-a33d095c62a5"),
                                    Value = new DateOnly(2025, 4, 9)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("82c1c5b0-a65c-406a-bc79-8e8d8de58ef8"),
                                    Value = new DateOnly(2022, 4, 3)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("5f36a8ad-97e6-424d-ad93-a8019daf2d6a"),
                                    Value = new DateOnly(2026, 7, 22)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("b818ae64-8e64-437a-870b-62b8542b4b23"),
                                    Value = new DateOnly(2026, 4, 9)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("39e6221d-fee0-42a2-bb94-1c9cc24843e8"),
                                    Value = new DateOnly(2027, 2, 3)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("96d54ef4-fc11-43f1-b0b0-06a0e0378bfc"),
                                    Value = new DateOnly(2025, 12, 22)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("4686ebb6-3345-40b5-8ace-e1ad26fef857"),
                                    Value = new DateOnly(2027, 4, 30)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("c6597222-1302-4d8d-ab27-08f24a0cfbef"),
                                    Value = new DateOnly(2023, 9, 29)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("4ac266fc-117d-4dbe-b3d2-7f002f76e4f9"),
                                    Value = new DateOnly(2026, 6, 11)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("251ab013-66b1-4ca8-9192-d50d7c971400"),
                                    Value = new DateOnly(2025, 8, 28)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("deecc17a-f088-4003-89e6-81c0c9b38d00"),
                                    Value = new DateOnly(2025, 2, 15)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("46ce2aaa-f175-4268-a4cb-b66e4e581dd9"),
                                    Value = new DateOnly(2026, 10, 24)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("b6a75246-6c38-409a-a630-0e157644b737"),
                                    Value = new DateOnly(2023, 9, 21)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("3e5dca62-8777-4645-8f9f-2b0268c40a0f"),
                                    Value = new DateOnly(2023, 8, 25)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("fb2a5e54-d46b-4fd6-811f-c9e1e96d0325"),
                                    Value = new DateOnly(2024, 4, 13)
                                },
                                new
                                {
                                    WeatherForecastId = new Guid("7ee8f27c-e0b3-43a1-94c6-48d08c8ec2fd"),
                                    Value = new DateOnly(2021, 11, 10)
                                });
                        });

                    b.Navigation("Date")
                        .IsRequired();

                    b.Navigation("Temperature")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
