name: .NET

on:
  push:
    branches: 
      - "main"
      - "develop"
  pull_request:
    branches: 
      - "main"
      - "develop"
  workflow_dispatch:

  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore src/CleanArchitecture.Template.sln

      - name: Build
        run: dotnet build src/CleanArchitecture.Template.sln --no-restore

      - name: Test
        run: dotnet test src/CleanArchitecture.Template.sln --no-build --verbosity normal
